---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: platform-api
  labels:
    app: api
    managed-by: gitops
spec:
  type: ClusterIP
  selector:
    app: api
    version: v1
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
