# Markdownlint configuration
default: true

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 4

# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  siblings_only: true

# MD029/ol-prefix - Ordered list item prefix
MD029:
  style: ordered

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements: [a, pre, br]

MD060: false
