---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: platform-web-dev
  labels:
    app: web
    environment: dev
    managed-by: gitops
data:
  HOST: "0.0.0.0"
  PORT: "4321"
  NODE_ENV: "production"
  PUBLIC_API_URL: "http://api.platform-api-dev:8000"
