---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-web-dev

resources:
  - ../../base/web
  - namespace.yaml
  - configmap.yaml
  - service.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
