---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: platform-web-dev
  labels:
    app: web
    environment: dev
    managed-by: gitops
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: 4321
      targetPort: http
      protocol: TCP
