apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: platform-api-dev
  labels:
    app: api
    environment: dev
    managed-by: gitops
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
