---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: platform-web
  labels:
    app: web
    managed-by: gitops
spec:
  type: ClusterIP
  selector:
    app: web
    version: v1
  ports:
    - name: http
      port: 4321
      targetPort: http
      protocol: TCP
